version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres
        ports: 
            - 5432:5432
        env_file: 
            ./.env
        volumes: 
            # - ./db:/var/lib/postgresql/data
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080
    url_shortener_api:
        container_name: url_shortener_api
        build: .
        env_file: 
            ./.env
        ports: 
            - 1323:1323